services:
  - type: web
    name: multi_agent_system
    runtime: python
    plan: free
    autoDeploy: false
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn src.ai_cv_advisor.app.api:app --host 0.0.0.0
    region: frankfurt